### ISSUE TITLE
Null return

### ISSUE THREAD

**Issue by 1ouis-xiii** [Shawey/Ebay-Scraper#2]
Why does the script sometimes return all zeros even though the URL is correct and there are items?

{'price': 0, 'shipping': 0, 'total': 0}

**Comment by alexis-brosseau** [comment]
Hey, I can't recreate your issue could you send an example ? I also fixed a lot of the code so it may work now.

**Comment by 1ouis-xiii** [comment]
averagePrice = EbayScraper.Average('iphone 12 lcd screen', 'uk', 'all')

I'll try the new code and see if it has fixed it

**Comment by 1ouis-xiii** [comment]
the new script returns below - which doesn't look right.... 

{'price': 2480.93, 'shipping': 20.23, 'total': 2501.16}

**Comment by alexis-brosseau** [comment]
I changed how the script get the prices. I tested it and it should work fine now. 

When I run your example with the new script I get : 
{'price': 27.82, 'shipping': 11.42, 'total': 39.24}
